global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
  - rules/rabbitmq_rules.yml

scrape_configs:
  - job_name: 'rms-integration-service-regions'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['rms-integration-service-us:8080']
        labels:
          region: 'us'
      - targets: ['rms-integration-service-europe:8080']
        labels:
          region: 'europe'
      - targets: ['rms-integration-service-asia:8080']
        labels:
          region: 'asia'

  - job_name: 'pricelogix-feed-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['pricelogix-feed-service:8081']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: '/metrics'

  - job_name: 'file-processing-metrics'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['rms-integration-service-us:8080']
        labels:
          region: 'us'
          metric_type: 'file_processing'
      - targets: ['rms-integration-service-europe:8080']
        labels:
          region: 'europe'
          metric_type: 'file_processing'
      - targets: ['rms-integration-service-asia:8080']
        labels:
          region: 'asia'
          metric_type: 'file_processing'
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'