name: CI/CD Pipeline

on: 
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
        
    - name: Build and Test
      run: ./gradlew build test

    - name: Run Integration Tests
      run: ./gradlew integrationTest
      
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Run Security Scan
      uses: anchore/scan-action@v3
      with:
        path: "."
        fail-build: true
        severity-cutoff: high

  regional-validation:
    needs: [test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [us, europe, asia]
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up test directories
      run: |
        mkdir -p ./${{ matrix.region }}-region/local
        mkdir -p ./${{ matrix.region }}-region/archive
        mkdir -p ./${{ matrix.region }}-region/error
        
    - name: Validate regional directory structure
      run: |
        test -d ./${{ matrix.region }}-region/local
        test -d ./${{ matrix.region }}-region/archive
        test -d ./${{ matrix.region }}-region/error

  docker:
    needs: [test, security-scan, regional-validation]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and test regional services
      run: |
        docker-compose build
        docker-compose up -d
        sleep 30
        
        # Validate US region service
        docker-compose exec -T rms-integration-service-us curl -f http://localhost:8080/actuator/health
        
        # Validate Europe region service
        docker-compose exec -T rms-integration-service-europe curl -f http://localhost:8080/actuator/health
        
        # Validate Asia region service
        docker-compose exec -T rms-integration-service-asia curl -f http://localhost:8080/actuator/health
        
        # Validate supporting services
        docker-compose exec -T rabbitmq rabbitmq-diagnostics check_port_connectivity
        docker-compose exec -T prometheus wget --no-verbose --tries=1 --spider http://localhost:9090/-/healthy
        docker-compose exec -T grafana wget --no-verbose --tries=1 --spider http://localhost:3000/api/health
        
        docker-compose down

    - name: Push images
      if: success()
      run: |
        echo "Publishing images to registry"
        # Add commands to push images to your container registry
